# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe313de171198ca2bd45d1133b6777deb86c86155014d19bc8c92e2ff454f55e0cf22df8f0aab13ea722a054452cffcac7b2365ab12b033386a0a1718c40422

test:
  secret_key_base: 1bcb5954d5edc9189dab3c321c4f97fd106f6ea9bac25f22c8292e878a7b8bc3f69a85a69b5e61b56133b128e01459bc28c06308ee154d78f6ad2156f0aa0f06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
